name: Build Marble

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up MinGW
      uses: egor-tensin/setup-mingw@v1
      with:
        version: '8.1.0'

    - name: Set up Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.14.0'
        host: 'windows'
        arch: 'win64'

    - name: Install dependencies
      run: |
        sudo apt-get install zlib1g-dev

    - name: Configure with CMake
      run: |
        cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH="C:/Qt/5.14.0/msvc2017_64" .

    - name: Build with CMake
      run: |
        mingw32-make
